
services:
  - name: web
    type: web
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGODB_URI
        sync: false  # Set this in Render's dashboard
      - key: NEXT_PUBLIC_SERVER_URL
        sync: false  # Set to your Render app URL

  - name: background-worker
    type: worker
    env: node
    buildCommand: npm install && npm run build
    startCommand: node scripts/worker.js
    envVars:
      - key: NODE_ENV
        value: production
